### ISSUE TITLE
Lab no. 7 : Azure app not the calling APIs

### ISSUE THREAD

**Issue by husseinsa** [chtrembl/azure-cloud#43]
Hi @chtrembl 
I am using this project to introduce Azure to our folks.

When following lab no. 7, I updated the Application Settings "PETSTOREPETSERVICE_URL" to point to the public IP of Ingress controller:

![image](https://github.com/chtrembl/azure-cloud/assets/22456321/043a899d-2da5-4e77-ae73-f51b21892158)

However, when I browse the App,  and navigate to "Shop by breeds", it doesn't work:
![image](https://github.com/chtrembl/azure-cloud/assets/22456321/dfe38225-2371-4c60-af41-1fe4a4538ea6)

### Troubleshooting:

1. Accessing  the API through external ingress IP is working fine:

![image](https://github.com/chtrembl/azure-cloud/assets/22456321/d9c28649-3934-457c-a36e-f0b4d84ba260)

2. Trying to access the same API endpoint got when accessing "Shop by breeds":

` curl -v http://20.246.239.92/petstorepetservice/v2/pet/findByStatus?status=available`

   ```
 Trying 20.246.239.92:80...
    * TCP_NODELAY set
    * Connected to 20.246.239.92 (20.246.239.92) port 80 (#0)
    > GET /petstorepetservice/v2/pet/findByStatus?status=available HTTP/1.1
    > Host: 20.246.239.92
    > User-Agent: curl/7.68.0
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 501
    < Date: Wed, 07 Feb 2024 20:17:18 GMT
    < Content-Length: 0
    < Connection: keep-alive
    <
    * Connection #0 to host 20.246.239.92 left intact

```

**Comment by chtrembl** [comment]
Thanks for reaching out @husseinsa and glad to see your using Azure Pet Store.

Can you please try adding the following 4 config properties

PETSTOREPETSERVICE_URL=[your ip for ingress]
PETSTORESERVICES_SUBSCRIPTION_KEY=blank
PETSTORE_APIM_HOST=blank

I'm wondering if I introduced a dependency on these APIM params that do not come up until a later guide. If this works please let me know and I will update this guide.

**Comment by chtrembl** [comment]
I was able to reproduce the 400 errors and made a fix that should be all set with the latest commit, as mentioned I reproduced the 400 errors, not sure on that 501, looks like an extra slash in the above screenshot ":8081//"

Please pull [latest](https://github.com/chtrembl/azure-cloud/commit/f18de8de9fe55304ed6c76209f14ad199d222401) commit 

The "HOST" header is now a conditional header and only set when PETSTORE_APIM_HOST is present (not needed until guide 9, didn't realize this was breaking the NGINX ingress, thanks for pointing this out, I should write some regression tests :) )

make sure your application.yml still has the petstore.apim.host property commented out (it should be by default until guide 9)

from your local machine if you can still get a 200 from the following: (looks like the cluster is stopped when I tried with yours)

```curl -H "Content-Type: application/json" http://20.246.239.92/petstorepetservice/v2/pet/findByStatus\?status\=available```

then try:
```docker build -t petstoreapp .```
```docker run --rm --name petstoreapp -p 8080:8080 -e PETSTOREAPP_SERVER_PORT=8080 -e PETSTOREPETSERVICE_URL=http://20.246.239.92/ petstoreapp:latest```

Azure App Service set:
PETSTOREAPP_SERVER_PORT=8080
PETSTOREPETSERVICE_URL=http://20.246.239.92/ 
PETSTOREPRODUCTSERVICE_URL=http://20.246.239.92/ 
PETSTOREORDERSERVICE_URL=http://20.246.239.92/ 

Please keep me posted. Thanks.

**Comment by husseinsa** [comment]
It's working now. Thanks!
There is another issue in the ci/cd lab for the kubernetes. If you can give permission, i can push the new fix and create a PR.

**Comment by chtrembl** [comment]
Thanks for assisting @husseinsa, you are now a collaborator, welcome aboard!. Please submit a PR.
