### ISSUE TITLE
deprecated upload-artifact

### ISSUE THREAD

**Issue by sahibgasimov** [chtrembl/azure-cloud#58]
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

![image](https://github.com/user-attachments/assets/0ac0e3b2-78bc-42de-89d0-b4e0d3d82dfe)

Solution:
Change 'v1' to  'v3'  here: https://github.com/chtrembl/azure-cloud/blob/59efd9e011d3c11d18ee5d8c32f6981600133c52/.github/workflows/petstoreapp_ci_cd_to_appservice.yml#L43

I tried to create a pull request but was not able to so opened this under Issue. Thanks for this project.

**Comment by drewcodes0001** [comment]
I also have the same issue. I get the same error when I click "Run workflow" in Actions. I am assuming this is why pushing changes to my repository doesn't trigger Actions.

**Comment by drewcodes0001** [comment]
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> 
> ![image](https://private-user-images.githubusercontent.com/100177153/375621846-0ac0e3b2-78bc-42de-89d0-b4e0d3d82dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2ODcwMDEsIm5iZiI6MTcyODY4NjcwMSwicGF0aCI6Ii8xMDAxNzcxNTMvMzc1NjIxODQ2LTBhYzBlM2IyLTc4YmMtNDJkZS04OWQwLWI0ZTBkM2Q4MmRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQyMjQ1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmYyM2NlODIyMWJjZWYxNWFlNGI1ZTk2OTA3YWFlNmIzMGYwODBkMDMyNzVmY2RkYmM0YjM3ODI3NjEzYWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1mVxL0THk0O3XDAQOVMCck7aNYMeVQ87wk0V_mEnJp0)
> 
> Solution: Change 'v1' to 'v3' here:
> 
> https://github.com/chtrembl/azure-cloud/blob/59efd9e011d3c11d18ee5d8c32f6981600133c52/.github/workflows/petstoreapp_ci_cd_to_appservice.yml#L43
> 
> I tried to create a pull request but was not able to so opened this under Issue. Thanks for this project.

There is a step that is kind of easy to miss. You can delete the "Upload Maven build artifact" task and that allowed me to run the workflow without error. Unfortunately my GitHub Actions still isn't being triggered when committing and pushing. Any ideas on why that may be?

**Comment by chtrembl** [comment]
Thanks all, just updated. This upload is really just for academic purposes to view/download the artifact etc... Hope you enjoy the project.
